[package]
name = "sim-something"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.8.0", features=["dynamic", "trace"] }
bevy-inspector-egui = "0.12"
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap.git", branch = "main" }
futures-lite = "1.12.0"
pathfinding = "3.0.13"
multimap = "0.8.3"
bevy_prototype_lyon = "0.6.0"
tracing = "0.1.35"
tracing-subscriber = "0.3.15"
bevy_mouse_tracking_plugin = "0.3"
bevy_prototype_debug_lines = "0.8"
fasthash = "0.4.0"
rand = "0.8.5"