on: [pull_request]    

name: Check

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Install dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - uses: actions-rs/clippy-check@v1
        name: Run Clippy
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
